name: Tutor_CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
<<<<<<< HEAD
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=W291,W292,W293,E3,E9 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
=======
    - name: Install dependencies(flake8 and pytest included)
      run: |
        ./bootstrap.sh
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=W292,W293,E3,E9 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run python3 -m pytest
>>>>>>> d1e87f5... Update Tutor_CI.yml
